server:
  port: 8080
  servlet:
    context-path: /mac-courses

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: postgres://etbctnrtcwkamm:7a96eac79d57826151fad87b912799e63c9e725d87de20478f06cd5506b0eac1@ec2-3-233-7-12.compute-1.amazonaws.com:5432/dbi4dvmk77kn5t
    username: etbctnrtcwkamm
    password: 7a96eac79d57826151fad87b912799e63c9e725d87de20478f06cd5506b0eac1
  jpa: 
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: false
    hibernate:
      ddl-auto: none

application:
  description: MAC-Courses

maccourses:
  jwt:
    expiracao: 7200000
    secret: "DE2EDBCE3E86603316B9C03AB2ABAECE1AA3551CD76338732E8371EE5D1355D3"